package:
  name: metis4py
  version: 5.1.0

source:
  git_url: https://github.com/dfroger/metis4py

build:
  number: 1
  binary_relocation: true

requirements:
  build:
    - python
    #- swig
    - metis
    - numpy
  run:
    - python
    - metis
    - numpy

about:
  home: https://github.com/dfroger/metis4py
  license: GPL3
