package:
  name: metis4py
  version: 5.1.0.3

source:
  fn: metis4py-5.1.0.3.tar.gz
  url: https://github.com/dfroger/metis4py/archive/5.1.0.3.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - python
    - swig
    - metis
    - numpy
  run:
    - python
    - metis
    - numpy

test:
  files:
    - ../test/test_metis4py.py
  commands:
    -  python test_metis4py.py

about:
  home: https://github.com/dfroger/metis4py
  license: GPL3
  summary: Python bindings for metis
